//! Which system units DaemonHall may control without a password.
//!
//! The answer is cyberwatch's watch list (auto-discovered units whose
//! program lives in your home, plus `extra_units`, minus `ignore`),
//! narrowed to unit files that an admin installed by hand: regular files
//! directly in /etc/systemd/system. Distro units (/usr/lib/systemd) and the
//! symlinks in /etc/systemd/system (aliases like display-manager.service,
//! `*.wants/` enablement links) are never on it, whatever the config says.

use crate::unitgen::valid_unit_name;
use std::path::Path;

pub const SYSTEM_DIR: &str = "/etc/systemd/system";
pub const RULES_PATH: &str = "/etc/polkit-1/rules.d/50-daemonhall.rules";

/// True if `name` is a hand-installed unit file in /etc/systemd/system.
pub fn is_admin_unit_file(name: &str) -> bool {
    valid_unit_name(name)
        && std::fs::symlink_metadata(Path::new(SYSTEM_DIR).join(name))
            .map(|m| m.file_type().is_file())
            .unwrap_or(false)
}

/// System units on `home`'s cyberwatch watch list that DaemonHall may
/// start/stop/restart, enable/disable and delete.
pub fn managed_system_units(home: &Path) -> Vec<String> {
    let cfg = cyberwatch::config::load_from(&cyberwatch::config::config_path_in(home))
        .unwrap_or_default();
    let mut units: Vec<String> = cyberwatch::discover::discover_units_in(&cfg, home)
        .into_iter()
        .filter(|id| !id.starts_with(cyberwatch::unit::USER_PREFIX))
        .filter(|name| is_admin_unit_file(name))
        .collect();
    units.sort();
    units.dedup();
    units
}

/// The polkit rule that grants `user` exactly this: run the DaemonHall
/// helper (which re-validates every request itself), and start / stop /
/// restart / reload the listed units. Nothing else changes; every other
/// unit and action still asks for a password.
pub fn polkit_rules(user: &str, units: &[String]) -> String {
    let units_js = serde_json::to_string(units).unwrap_or_else(|_| "[]".into());
    let user_js = serde_json::to_string(user).unwrap_or_else(|_| "\"\"".into());
    format!(
        r#"// Generated by daemonhall-unitctl (cybercore-tech/DaemonHall). Do not edit:
// it's rewritten whenever DaemonHall's watch list changes.
//
// Lets {user} run the DaemonHall helper, which validates everything it does,
// and start/stop/restart/reload ONLY the units below, without a password.
// Every other unit and action still asks for one.
polkit.addRule(function(action, subject) {{
    if (subject.user !== {user_js}) return polkit.Result.NOT_HANDLED;
    if (action.id === "{action}") return polkit.Result.YES;
    if (action.id === "org.freedesktop.systemd1.manage-units") {{
        var units = {units_js};
        var verbs = ["start", "stop", "restart", "reload", "try-restart",
                     "reload-or-restart", "reload-or-try-restart"];
        if (units.indexOf(action.lookup("unit")) >= 0 &&
            verbs.indexOf(action.lookup("verb")) >= 0) {{
            return polkit.Result.YES;
        }}
    }}
    return polkit.Result.NOT_HANDLED;
}});
"#,
        action = crate::POLKIT_ACTION,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rules_embed_user_units_and_action() {
        let r = polkit_rules("raven", &["wraithflow.service".into(), "a\"b".into()]);
        assert!(r.contains(r#"subject.user !== "raven""#));
        assert!(r.contains(r#"["wraithflow.service","a\"b"]"#));
        assert!(r.contains(crate::POLKIT_ACTION));
    }

    #[test]
    fn symlinks_and_bad_names_are_never_admin_units() {
        assert!(!is_admin_unit_file("../passwd.service"));
        assert!(!is_admin_unit_file("getty@.service"));
        // display-manager.service is a symlink on systemd systems.
        assert!(!is_admin_unit_file("display-manager.service"));
    }
}
